### ISSUE TITLE
Make all JSON generated or consumed by the server conform to Avro schema

### ISSUE THREAD

**Issue by diekhans** [ga4gh/schemas#313] opened 2015-05-28 19:07 UTC
The Java JSON deserializer does not work with some of the JSON generated by the reference server.  Instead of continuing to hack around this, lets just make the JSON conform.

Our conformance suite contractor is going to create a standalone program to test a file of json to see if it is valid against the schema.  Lets figure out how to get releases of the server for him and others to work with.

**Comment by wstidolph** [comment] 2015-05-29 02:48
The avro-tools can do this, so I'm not going to make a standalone tool unless this approach is adequate to the purpose - [here's my writeup] (https://docs.google.com/document/d/18ED_Rv5NgqingWtit2okM4AWt48J2ANLvEPSBHzghhE/edit?usp=sharing)

**Comment by diekhans** [comment] 2015-05-29 02:51
The avro tools jar provides a utility we can use to validate a given JSON file against a given Avro Schema (*.avsc):

java -jar avro-tools-1.7.7.jar jsontofrag --schema-file Individual.avsc BadIndividual.json
Exception in thread "main" org.apache.avro.AvroTypeException: Expected field name not found: id
        at org.apache.avro.io.JsonDecoder.doAction(JsonDecoder.java:477)
…

If the JSON validates then a binary object is produced and can be discarded (only STDERR is interesting). On Windows, this might done with, e.g.:

java -jar avro-tools-1.7.7.jar jsontofrag --schema-file Individual.avsc BadIndividual.json >>NUL

Normal command line handling applies; for example, in a bash environment, the STDOUT can be dropped and the STDERR can be piped to cleanup or logging, etc:

java -jar avro-tools-1.7.7.jar jsontofrag --schema-file OntologyTerm.avsc RandomOntologyTerm.json 2>&1 > /dev/null | head -n 2

In a bash script, a ‘java .. jsontofrag’ exit status ($?) of 0 indicates a “good” parse, while an exit status of “1” indicates a bad parse.

This validation assumes the JSON is what would have been generated by a process that creates a JSON representation of the data, without the schema (as is done in GA4GH). An example generating process starting from a GA4GH schema would be:

java -jar avro-tools-1.7.7.jar random --schema-file ReadGroupSet.avsc --count 1 ReadGroupSet.datum

java -jar avro-tools-1.7.7.jar tojson --pretty ReadGroupSet.datum >> ReadGroupSet.json

The resulting JSON (in this case ReadGroupSet.json with dummy data embedded) can be easily edited to create bad-data test cases or examined to see the expected structure implied by the *.avsc

**Comment by jeromekelleher** [comment] 2015-05-29 08:23
Can you be more specific about what JSON is the Java deserialiser isn't working with? We've put a lot of effort into making sure that the output is validated against the schema in the reference server, so I'm surprised and disappointed that this has happened. What version of the schema is the client using, and what version of the server are the running against?

We have quite a lot of technology for validating the JSON against the schema in the reference server. This is based on the Python Avro package's `validate` method. We also have some code in place to identify incorrect fields, to provide more useful error responses when the client sends invalid JSON (see issue https://github.com/ga4gh/server/issues/382 for more details).

Since we already have these tools in place, I think it would be more easier to develop a validator within the reference implementation infrastructure.

**Comment by wstidolph** [comment] 2015-06-06 16:24
This isn't quite a "schema" problem (in terms of information structure) but what I'm learning is that the communications mismatch I'm experiencing is that Avro's JSON to/from disk (which is what we get from the Avro encoder/decoder) has two differences from "normal" JSON: (1) order sensitivity, and (2) embedded type information.

(1) Order sensitivity is that the Avro decoder walks the JSON string and expects every field to be present (with a value 'null' if need be) and in the order it expects.

(2) AVRO-generated JSON (whether made using avro-tools, or in java directly using Avro's DatumWriter with a JsonEncoder)  includes data types in the field bodies, but as best I can tell the Ref Server JSON does not.

For example, if you generate a ReadGroupSet object as described above, you get a json string like this:
```
{
  "id" : "cxarbpx",
  "datasetId" : {
    "string" : "hfukcvioeadbef"
  },
  "name" : {
    "string" : "jrdovkmwrrvucnp"
  },
```
Avro can deserialize that "Avro-JSON" into an Avro code-generated Java class.

The Ref Server JSON seems to be simpler, just normal JSON like:
```
{
  "id" : "cxarbpx",
  "datasetId" : "hfukcvioeadbef",
  "name" : "jrdovkmwrrvucnp",
```

Avro won't deserialize this, it's missing the expected type information structure. 

To test the Server's response to the "Avro-JSON" I confirmed that the server generates a sane-looking response (16 'variants' entries) to this "normal" JSON:

    {"variantSetIds":["1kg-phase1"],"referenceName":"22", "start":16050408, "end":16052159}

But when this query is "AVRO"-ized to:
    {"variantSetIds":["1kg-phase1"],"referenceName":{"string":"22"},
     "start":{"long":16050408}, "end":{"long":16052159}} 

then the Server returns:
    {
     errorCode: 3424984409
     message: "Internal Server Error"
    }
(Note this is missing a comma after the first field)

**Comment by jeromekelleher** [comment] 2015-06-08 09:26
Thanks for this @wstidolph. I'm surprised that Avro's serialisation code does this, but I think the conclusion is pretty clear: we can't use Avro's serialisation code for the GA4GH API. The ordering requirement means that Avro does not implement JSON correctly, since "An object is an unordered set of name/value pairs. " according to http://json.org. The extra type information has never been mentioned as being part of the GA4GH protocol, and I'm pretty sure no current server implementation supports it.

So, Avro's JSON-like serialisation format is of no use to us.

On another point, can you open an issue on the reference server if it is returning malformed JSON in error conditions please? I can't seem to reproduce the case you've given above. If we are returning malformed JSON this is a bug and we'll fix it immediately.

**Comment by ekg** [comment] 2015-06-08 12:47
One might say we should file a bug against avro, but is this really what we should be focusing on?

It seems like avro would need quite a bit of refinement to be useful here without issue.

What projects are using it?

**Comment by jeromekelleher** [comment] 2015-06-08 12:52
@ekg --- indeed. Becoming increasingly disillusioned with Avro...

**Comment by david4096** [comment] 2017-03-09 05:13
Closing due to move to protobuf which provides a nice JSON serialization layer.

**Closed by david4096** 2017-03-09 05:13 UTC
